package com.ciphervault.enums;

public enum AuditAction {
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	SIGNUP,
	PASSWORD_RESET_REQUESTED,
	PASSWORD_RESET_COMPLETED,
	FILE_UPLOADED,
	FILE_DOWNLOADED,
	FILE_DELETED,
	FILE_RESTORED,
	FILE_PURGED,
	SHARE_CREATED,
	OAUTH_LOGIN,
	ADMIN_USER_DELETED,
	ADMIN_ROLE_CHANGED
}
